/* Generated by Yosys 0.68 (git sha1 38e001a6f, GNU /usr/bin/c++ 13.3.0) */

(* top =  1  *)
(* src = "/mnt/c/Users/Devansh/GEM/test_dsp.v:1.1-20.10" *)
module test_dsp(clk, a, b, c, p);
  (* src = "/mnt/c/Users/Devansh/GEM/test_dsp.v:2.17-2.20" *)
  input clk;
  wire clk;
  (* src = "/mnt/c/Users/Devansh/GEM/test_dsp.v:3.24-3.25" *)
  input [26:0] a;
  wire [26:0] a;
  (* src = "/mnt/c/Users/Devansh/GEM/test_dsp.v:4.24-4.25" *)
  input [17:0] b;
  wire [17:0] b;
  (* src = "/mnt/c/Users/Devansh/GEM/test_dsp.v:5.24-5.25" *)
  input [47:0] c;
  wire [47:0] c;
  (* src = "/mnt/c/Users/Devansh/GEM/test_dsp.v:6.24-6.25" *)
  output [47:0] p;
  wire [47:0] p;
  (* src = "/mnt/c/Users/Devansh/GEM/test_dsp.v:12.7-18.6|/mnt/c/Users/Devansh/GEM/aigpdk/gemmacro_map.v:150.22-150.39" *)
  wire _00_;
  (* src = "/mnt/c/Users/Devansh/GEM/test_dsp.v:12.7-18.6|/mnt/c/Users/Devansh/GEM/aigpdk/gemmacro_map.v:150.45-150.62" *)
  wire _01_;
  (* src = "/mnt/c/Users/Devansh/GEM/test_dsp.v:12.7-18.6|/mnt/c/Users/Devansh/GEM/aigpdk/gemmacro_map.v:152.17-152.31" *)
  wire _02_;
  (* src = "/mnt/c/Users/Devansh/GEM/test_dsp.v:12.7-18.6|/mnt/c/Users/Devansh/GEM/aigpdk/gemmacro_map.v:153.17-153.31" *)
  wire _03_;
  (* src = "/mnt/c/Users/Devansh/GEM/test_dsp.v:12.7-18.6|/mnt/c/Users/Devansh/GEM/aigpdk/gemmacro_map.v:150.21-150.63" *)
  wire _04_;
  (* src = "/mnt/c/Users/Devansh/GEM/test_dsp.v:12.7-18.6|/mnt/c/Users/Devansh/GEM/aigpdk/gemmacro_map.v:152.9-152.31" *)
  wire _05_;
  (* src = "/mnt/c/Users/Devansh/GEM/test_dsp.v:12.7-18.6|/mnt/c/Users/Devansh/GEM/aigpdk/gemmacro_map.v:153.9-153.31" *)
  wire _06_;
  (* src = "/mnt/c/Users/Devansh/GEM/test_dsp.v:12.7-18.6|/mnt/c/Users/Devansh/GEM/aigpdk/gemmacro_map.v:152.8-154.39" *)
  wire [1:0] _07_;
  (* src = "/mnt/c/Users/Devansh/GEM/test_dsp.v:12.7-18.6|/mnt/c/Users/Devansh/GEM/aigpdk/gemmacro_map.v:153.8-154.39" *)
  wire [1:0] _08_;
  (* src = "/mnt/c/Users/Devansh/GEM/test_dsp.v:12.7-18.6|/mnt/c/Users/Devansh/GEM/aigpdk/gemmacro_map.v:148.21-148.48" *)
  (* unused_bits = "7 8" *)
  wire [8:0] _09_;
  (* src = "/mnt/c/Users/Devansh/GEM/test_dsp.v:12.7-18.6|/mnt/c/Users/Devansh/GEM/aigpdk/gemmacro_map.v:163.16-163.39" *)
  wire _10_;
  (* src = "/mnt/c/Users/Devansh/GEM/test_dsp.v:12.7-18.6|/mnt/c/Users/Devansh/GEM/aigpdk/gemmacro_map.v:46.45-46.48" *)
  wire _11_;
  (* src = "/mnt/c/Users/Devansh/GEM/test_dsp.v:12.7-18.6|/mnt/c/Users/Devansh/GEM/aigpdk/gemmacro_map.v:48.17-48.18" *)
  wire [26:0] _12_;
  assign _00_ = _09_[1:0] == (* src = "/mnt/c/Users/Devansh/GEM/test_dsp.v:12.7-18.6|/mnt/c/Users/Devansh/GEM/aigpdk/gemmacro_map.v:150.22-150.39" *) 2'h1;
  assign _01_ = _09_[3:2] == (* src = "/mnt/c/Users/Devansh/GEM/test_dsp.v:12.7-18.6|/mnt/c/Users/Devansh/GEM/aigpdk/gemmacro_map.v:150.45-150.62" *) 2'h1;
  assign _02_ = _09_[6:4] == (* src = "/mnt/c/Users/Devansh/GEM/test_dsp.v:12.7-18.6|/mnt/c/Users/Devansh/GEM/aigpdk/gemmacro_map.v:152.17-152.31" *) 3'h2;
  assign _03_ = ! (* src = "/mnt/c/Users/Devansh/GEM/test_dsp.v:12.7-18.6|/mnt/c/Users/Devansh/GEM/aigpdk/gemmacro_map.v:153.17-153.31" *) _09_[6:4];
  assign _04_ = _00_ && (* src = "/mnt/c/Users/Devansh/GEM/test_dsp.v:12.7-18.6|/mnt/c/Users/Devansh/GEM/aigpdk/gemmacro_map.v:150.21-150.63" *) _01_;
  assign _05_ = _04_ && (* src = "/mnt/c/Users/Devansh/GEM/test_dsp.v:12.7-18.6|/mnt/c/Users/Devansh/GEM/aigpdk/gemmacro_map.v:152.9-152.31" *) _02_;
  assign _06_ = _04_ && (* src = "/mnt/c/Users/Devansh/GEM/test_dsp.v:12.7-18.6|/mnt/c/Users/Devansh/GEM/aigpdk/gemmacro_map.v:153.9-153.31" *) _03_;
  assign _07_ = _05_ ? (* src = "/mnt/c/Users/Devansh/GEM/test_dsp.v:12.7-18.6|/mnt/c/Users/Devansh/GEM/aigpdk/gemmacro_map.v:152.8-154.39" *) 2'h2 : _08_;
  assign _08_ = _06_ ? (* src = "/mnt/c/Users/Devansh/GEM/test_dsp.v:12.7-18.6|/mnt/c/Users/Devansh/GEM/aigpdk/gemmacro_map.v:153.8-154.39" *) 2'h1 : 2'h0;
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Users/Devansh/GEM/test_dsp.v:12.7-18.6|/mnt/c/Users/Devansh/GEM/aigpdk/gemmacro_map.v:160.15-171.4" *)
  GEM_DSP48E2 dsp_inst (
    .A(a),
    .B(b),
    .C(c),
    .CEP(_11_),
    .CLK(clk),
    .D(_12_),
    .OPMODE_S(_07_),
    .P(p),
    .RSTP(_10_),
    .USE_D(1'h0)
  );
endmodule
